services:
  # qdrant:
  #   image: qdrant/qdrant:latest
  #   ports:
  #     - "6333:6333"
  #   volumes:
  #     - qdrant_data:/qdrant/storage

  api:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    # garante que o CSV esteja em /app/data/ dentro do container
    volumes:
      - ./data:/app/data

#volumes:
#  qdrant_data: