services:
  # Se quiser rodar Qdrant localmente:
  # qdrant:
  #   image: qdrant/qdrant:latest
  #   ports:
  #     - "6333:6333"
  #   volumes:
  #     - qdrant_data:/qdrant/storage

  api:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000

# Se usar Qdrant local:
#volumes:
#  qdrant_data:
